In [2]:
import numpy as np


In [64]:
arr = np.arange(25)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
arr[2:5]

array([2, 3, 4])

In [67]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [68]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [69]:
#Para asignar un valor en ciertas posiciones
arr[2:5] = 100

In [70]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [83]:
#Para referenciar a todas las posiciones se usa solo los dos puntos
arr[:] = 200


In [84]:
arr

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [85]:
arreglo2 = arr.copy()

In [87]:
arreglo2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [93]:
arreglo_2d = np.array([[1,2,3], [10,-2,1],[2,3,34]])

In [94]:
arreglo_2d

array([[ 1,  2,  3],
       [10, -2,  1],
       [ 2,  3, 34]])

In [95]:
arreglo_2d[0,2]

3

In [96]:
arreglo_2d[1:,1:]

array([[-2,  1],
       [ 3, 34]])

In [110]:
arreglo_2d[1][:]

array([10, -2,  1])

In [3]:
arr = np.arange(1,10)

In [4]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [5]:
# Crear un vector de valores booleanos
booleanArreglo = arr > 5


In [6]:
booleanArreglo

array([False, False, False, False, False,  True,  True,  True,  True])

In [7]:
#Con ayuda del vector booleano se muestran los valores que son mayores a 5 del arreglo arr
arr[booleanArreglo]

array([6, 7, 8, 9])

In [8]:
arr[arr>5]

array([6, 7, 8, 9])

In [37]:
arreglo_2d = np.arange(50).reshape(10,5)

In [36]:
arreglo_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [52]:
arreglo_2d[8,1:4]

array([41, 42, 43])

In [54]:
arreglo_2d[2:5,1:4]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

## 