In [2]:
import numpy as np

In [3]:
array = [1,2,3]


In [4]:
np.array(array)

array([1, 2, 3])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#Es parecido a np.arange() pero el tercer argumento hace referencia a la cantidad de numeros
# que se pueden obtener del intervalo indicado
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
# matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Crear vectores o matrices con numeros aleatorios con distribución uniforme
np.random.rand(5,3)

array([[0.72057685, 0.15921544, 0.0994203 ],
       [0.35322969, 0.37763031, 0.97174996],
       [0.21140329, 0.26184539, 0.86289475],
       [0.09409263, 0.22063866, 0.84607072],
       [0.21619545, 0.80403186, 0.89263976]])

In [26]:
#Crear vectores o matrices con numeros aleatorios con distribución normal
np.random.randn(5,3)

array([[ 0.6990028 , -0.77588949,  0.07636962],
       [-3.12481219,  2.17302834, -0.67010708],
       [ 0.77750268,  1.4549701 ,  0.69496882],
       [ 2.57994185,  0.15030872,  1.16398176],
       [-0.35900221, -1.32328792,  0.72529475]])

In [34]:
#Crea numeros aleatorios enteros, el primero argumento es el intervalo menor y el segundo
# argumento es el intervalo mayor en el cual el numero o estará, el tercer indica la cantidad
np.random.randint(70,100,2)

array([97, 70])

In [47]:
#Puedes cambiar la dimensión de un arreglo así:
arr = np.array([2,3,1,0,1,2])
arr.reshape(2,3)

array([[2, 3, 1],
       [0, 1, 2]])

In [56]:
arreglo = np.array([2,3,10,0])


In [51]:
#valor máximo del arreglo
arreglo.max()

10

In [52]:
# valor mínimo del arreglo
arreglo.min()

0

In [53]:
#posición del arreglo maximo
arreglo.argmax()

2

In [58]:
arreglo.shape

(4,)

In [59]:
arreglo.reshape(2,2)

array([[ 2,  3],
       [10,  0]])

In [62]:
#tipo de dato
arreglo.dtype

dtype('int32')