In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = arr + arr

In [5]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [8]:
arr = arr + 100

In [9]:
arr

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [10]:
arr**2

array([10000, 10404, 10816, 11236, 11664, 12100, 12544, 12996, 13456,
       13924], dtype=int32)

In [11]:
#Raíz
np.sqrt(arr)

array([10.        , 10.09950494, 10.19803903, 10.29563014, 10.39230485,
       10.48808848, 10.58300524, 10.67707825, 10.77032961, 10.86278049])

In [12]:
arr.max()

118

In [14]:
np.sin(arr)

array([-0.50636564,  0.99482679, -0.3216224 , -0.7271425 ,  0.92681851,
       -0.04424268, -0.8899956 ,  0.78498039,  0.23666139, -0.98195217])